name: CICD
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # lorsqu'on liste une permission il faut toutes les lister, et celles ci sont nécessaires : moindre privilège.
      contents: read
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Perform Bandit Analysis #SAST : auditer le code sans le run
        uses: PyCQA/bandit-action@v1
      - name: Check secret leaks #scan des secrets
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run pytest
        run: pytest -q

  build-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required to checkout and read repo files
      security-events: write # Required to upload SARIF files to Security tab
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Build an image from Dockerfile
        run: docker build -t api-tickets .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: "api-tickets"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
      - name: Run Trivy vulnerability scanner in IaC mode
        if: always()
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-ref: "."
          scan-type: "config"
          hide-progress: true
          format: "sarif"
          output: "trivy-results.sarif"
          exit-code: "1"
          severity: "CRITICAL,HIGH"
          limit-severities-for-sarif: true

      - name: Upload Trivy scan results to GitHub Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: "trivy-results.sarif"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        if: github.ref == 'refs/heads/main'
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-secure:latest, ${{ secrets.DOCKERHUB_USERNAME }}/api-secure:${{ github.sha }}
